apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: planetscale-operator.v0.1.7
  namespace: placeholder
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "planetscale.com/v1alpha1",
          "kind": "PsCluster",
          "metadata": {
            "name": "example"
          },
          "spec": {
            "monitored": true,
            "lockserver": {
              "endpoint": "<LockServer IP and Port>",
              "root_path": "/vitess/example/global"
            },
            "cells": [
              {
                "name": "example1",
                "useGlobalLockserver": true,
                "gateway": {
                  "count": 2
                },
                "vtctld": {
                  "count": 1
                },
                "keyspaces": [
                  {
                    "name": "messagedb",
                    "shards": [
                      {
                        "range": "-80",
                        "replicas": [
                          {
                            "type": "replica"
                          },
                          {
                            "type": "replica"
                          },
                          {
                            "type": "rdonly"
                          },
                          {
                            "type": "replica"
                          }
                        ]
                      },
                      {
                        "range": "80-",
                        "replicas": [
                          {
                            "type": "replica"
                          },
                          {
                            "type": "replica"
                          },
                          {
                            "type": "rdonly"
                          },
                          {
                            "type": "replica"
                          }
                        ]
                      }
                    ]
                  }
                ]
              }
            ]
          }
        }
      ]
    categories: "Database"
    certified: "False"
    description: PlanetScale Vitess is a database clustering system for horizontal scaling of MySQL.
    containerImage: registry.connect.redhat.com/planetscale/operator:0.1.7
    createdAt: 2019-02-06T20:00:00Z
    support: PlanetScale
spec:
  displayName: PlanetScale Operator
  description: |-
    # PlanetScale's Vitess Operator

    Vitess is a database clustering system for horizontal scaling of MySQL
    through generalized sharding.


    By encapsulating shard-routing logic, Vitess allows application code and
    database queries to remain agnostic to the distribution of data onto
    multiple shards. With Vitess, you can even split and merge shards as your
    needs grow, with an atomic cutover step that takes only a few seconds.


    Vitess has been a core component of YouTube's database infrastructure since
    2011, and has grown to encompass tens of thousands of MySQL nodes. For more
    information, visit [https://planetscale.com](https://planetscale.com)

    ## Before You Start

    1. Create a RedHat registry image pull secret called
    `planetscale-operator-pull-secret`, which is required to pull the operator
    image.

    2. Create an etcd cluster, which is used as a lock server by PlanetScale
    Vitess clusters.

    > **NOTE**:
    > * This operator only supports running in the same namespace as the PsCluster
    >   resources it is watching.
    > * This operator should be deployed in an isolated namespace since the pods
    >   it creates use the `default` service account and require the `use`
    >   permission on the `anyuid` security context contraint (SCC) to run
    >   correctly. Running this operator in a shared namespace is not recommended
    >   since unrelated pods will have access to use the `anyuid` SCC.

  keywords: ['mysql', 'vitess', 'sharding', 'database']
  version: 0.1.7
  maturity: alpha
  maintainers:
  - name: PlanetScale
    email: contact@planetscale.com
  links:
  - name: PlanetScale
    url: https://planetscale.com
  provider:
    name: PlanetScale
  labels:
    name: planetscale-operator
  selector:
    matchLabels:
      name: planetscale-operator
  installModes:
  - type: OwnNamespace
    supported: true
  - type: SingleNamespace
    supported: true
  - type: MultiNamespace
    supported: false
  - type: AllNamespaces
    supported: false
  install:
    strategy: deployment
    spec:
      clusterPermissions:
      - serviceAccountName: planetscale-operator
        rules:
        - apiGroups:
          - security.openshift.io
          resources:
          - securitycontextconstraints
          verbs:
          - use
          resourceNames:
          - anyuid
      - serviceAccountName: default
        rules:
        - apiGroups:
          - security.openshift.io
          resources:
          - securitycontextconstraints
          verbs:
          - use
          resourceNames:
          - anyuid
      - serviceAccountName: prometheus
        rules:
        - apiGroups:
          - ""
          resources:
          - nodes
          - services
          - endpoints
          - pods
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
        - nonResourceURLs:
          - "/metrics"
          verbs:
          - get
      permissions:
      - serviceAccountName: planetscale-operator
        rules:
        - apiGroups:
          - planetscale.com
          resources:
          - "*"
          verbs:
          - "*"
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - "*"
          verbs:
          - "*"
        - apiGroups:
          - etcd.database.coreos.com
          resources:
          - "*"
          verbs:
          - "*"
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumes
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - "*"
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - "*"
        - apiGroups:
          - extensions
          resources:
          - deployments
          verbs:
          - "*"
      deployments:
      - name: planetscale-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: planetscale-operator
          template:
            metadata:
              labels:
                name: planetscale-operator
            spec:
              serviceAccountName: planetscale-operator
              imagePullSecrets:
              - name: planetscale-operator-pull-secret
              containers:
                - name: planetscale-operator
                  image: registry.connect.redhat.com/planetscale/operator:0.1.7
                  ports:
                  - containerPort: 60000
                    name: metrics
                  workingDir: /usr/local/bin
                  command:
                  - /usr/local/bin/planetscale-operator
                  imagePullPolicy: Always
                  env:
                    - name: WATCH_NAMESPACE
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.annotations['olm.targetNamespaces']
                    - name: OPERATOR_NAME
                      value: "planetscale-operator"
  customresourcedefinitions:
    owned:
    - name: psclusters.planetscale.com
      version: v1alpha1
      kind: PsCluster
      displayName: PsCluster
      description: Instance of a PlanetScale Vitess Cluster
