apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: camel-k-operator.v0.1.0
  namespace: palceholder
  annotations:
    categories: "apache, kamel, kubernetes, serverless, microservices"
    certified: false 
    containerImage: docker.io/apache/camel-k
    createdAt: 2019-01-10T12:00:00Z
    support: Apache Camel Community
spec:
  displayName: Camel-K Operator
  description: |-
    Camel K (a.k.a Kamel) is a lightweight integration framework built from Apache Camel that runs natively on Kubernetes and is specifically designed for serverless and microservice architectures.
  keywords: ['apache', 'kamel', 'kubernetes', 'serverless', 'microservices']
  version: 0.1.0
  maintainers:
  - name: The Apache Software Foundation
    email: users@camel.apache.org
  provider:
    name: The Apache Software Foundation
  labels:
    name: camel-k-operator
  selector:
    matchLabels:
      name: camel-k-operator
  links:
  - name: Camel K Operator Source Code
    url: https://github.com/apache/camel-k
  installModes:
  - type: OwnNamespace
    supported: true
  - type: SingleNamespace
    supported: true
  - type: MultiNamespace
    supported: false
  - type: AllNamespaces
    supported: true
  install:
    strategy: deployment
    spec:
      permissions:
      - serviceAccountName: camel-k-operator
        rules:
        - apiGroups:
          - camel.apache.org
          resources:
          - "*"
          verbs:
          - "*"
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - configmaps
          - secrets
          verbs:
          - create
          - delete
          - deletecollection
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - deletecollection
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          attributeRestrictions: null
          resources:
          - daemonsets
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          - "build.openshift.io"
          resources:
          - buildconfigs
          - buildconfigs/webhooks
          - builds
          verbs:
          - create
          - delete
          - deletecollection
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          - "image.openshift.io"
          resources:
          - imagestreamimages
          - imagestreammappings
          - imagestreams
          - imagestreams/secrets
          - imagestreamtags
          verbs:
          - create
          - delete
          - deletecollection
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          - build.openshift.io
          attributeRestrictions: null
          resources:
          - buildconfigs/instantiate
          - buildconfigs/instantiatebinary
          - builds/clone
          verbs:
          - create
        - apiGroups:
          - ""
          - "route.openshift.io"
          resources:
          - routes
          verbs:
          - create
          - delete
          - deletecollection
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          - route.openshift.io
          resources:
          - routes/custom-host
          verbs:
          - create
      deployments:
      - name: camel-k-operator
        spec:
          replicas: 1
          strategy:
            type: Recreate
          selector:
            matchLabels:
              name: camel-k-operator
          template:
            metadata:
              labels:
                name: camel-k-operator
                camel.apache.org/component: operator
            spec:
              serviceAccountName: camel-k-operator
              containers:
                - name: camel-k-operator
                  image: docker.io/apache/camel-k:0.1.0
                  ports:
                  - containerPort: 60000
                    name: metrics
                  command:
                  - camel-k
                  imagePullPolicy: IfNotPresent
                  env:
                  - name: WATCH_NAMESPACE
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.annotations['olm.targetNamespaces']
                  - name: OPERATOR_NAME
                    value: "camel-k"
  customresourcedefinitions:
    owned:
    - name: integrations.camel.apache.org
      version: v1alpha1
      kind: Integration
      displayName: Integration CRD
      description: Integration CRD for Camel-K
    - name: integrationplatforms.camel.apache.org
      version: v1alpha1
      kind: IntegrationPlatform
      displayName: Integration Platforms CRD
      description: Integration Platforms CRD for Camel-K
    - name: integrationcontexts.camel.apache.org
      version: v1alpha1
      kind: IntegrationContext     
      displayName: Integration Context CRD
      description: Integration Context CRD for Camel-K
